### ISSUE TITLE
Add Website URL here on GitHub

### ISSUE THREAD

**Issue by szepeviktor** [RikudouSage/QrPaymentEU#32]
Could you add a Website URL in the top right About box with the cog?

- https://en.wikipedia.org/wiki/EPC_QR_code
- or https://www.europeanpaymentscouncil.eu/document-library/guidance-documents/quick-response-code-guidelines-enable-data-capture-initiation

**Comment by RikudouSage** [comment]
Done.

**Comment by szepeviktor** [comment]
Thank you.
