### ISSUE TITLE
incorrect EPC-QR data created - payment reference line missing

### ISSUE THREAD

**Issue by swurzinger** [RikudouSage/QrPaymentEU#43]
Unfortunately the plugin generates incorrect data, which makes banking apps fail to read the payment reference / remittance text.

Issue is that the code just ignores/skips the creditor reference line and thus all information following below is off by one line.

see specification:
https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2018-05/EPC069-12%20v2.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20a%20SCT.pdf

especially this part:
![image](https://user-images.githubusercontent.com/6787397/121860464-297e5400-ccf9-11eb-9971-b082a5d018df.png)

although you may specify either a creditor reference or a unstructured remittance text each one of them must go into their own line. check also the examples in the specification.

so creditor reference is always line 10 and unstructured remittance text is always line 11 (one of these two lines always have to be empty)

this implementation however, just merges the two things on a single line and thus unstructured remittance text goes to the wrong line and following data (like the "Beneficiary to originator information" field) ends up in the wrong line as well.

**Comment by swurzinger** [comment]
created a proposal for a fix, see #44

**Comment by RikudouSage** [comment]
Thanks for the report! Again sorry for not using your PR, I didn't notice it in time.
